// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Sep 14 2026 16:22:33 IST (Sep 14 2026 10:52:33 UTC)

// Verification Directory fv/top 

module RC_CG_MOD_2(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module top(clk, reset, start, multiplicand_in, multiplier_in,
     mult_complete, accumulated_prod);
  input clk, reset, start;
  input [3:0] multiplicand_in, multiplier_in;
  output mult_complete;
  output [7:0] accumulated_prod;
  wire clk, reset, start;
  wire [3:0] multiplicand_in, multiplier_in;
  wire mult_complete;
  wire [7:0] accumulated_prod;
  wire [3:0] u_datapath_loop_counter;
  wire [3:0] u_datapath_working_multiplicand;
  wire [1:0] u_controller_current_state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_36, n_37, n_38, n_39, rc_gclk, u_controller_n_13;
  wire u_datapath_n_166, u_datapath_rc_gclk_184;
  RC_CG_MOD_2 u_datapath_RC_CG_HIER_INST2(.enable (n_0), .ck_in (clk),
       .ck_out (u_datapath_rc_gclk_184), .test (1'b0));
  RC_CG_MOD RC_CG_DECLONE_HIER_INST(.enable (u_datapath_n_166), .ck_in
       (clk), .ck_out (rc_gclk), .test (1'b0));
  OAI21X1 g659__2398(.A0 (n_39), .A1 (n_33), .B0 (u_controller_n_13),
       .Y (u_datapath_n_166));
  INVX1 g660(.A (n_33), .Y (n_36));
  NOR2X1 g661__5107(.A (u_datapath_loop_counter[3]), .B (n_37), .Y
       (n_33));
  OR2X1 g662__6260(.A (u_datapath_loop_counter[2]), .B (n_38), .Y
       (n_37));
  DFFHQX1 \u_datapath_working_multiplicand_reg[1] (.CK
       (u_datapath_rc_gclk_184), .D (multiplicand_in[1]), .Q
       (u_datapath_working_multiplicand[1]));
  DFFHQX1 \u_datapath_working_multiplicand_reg[2] (.CK
       (u_datapath_rc_gclk_184), .D (multiplicand_in[2]), .Q
       (u_datapath_working_multiplicand[2]));
  DFFHQX1 \u_datapath_working_multiplicand_reg[3] (.CK
       (u_datapath_rc_gclk_184), .D (multiplicand_in[3]), .Q
       (u_datapath_working_multiplicand[3]));
  DFFQXL \u_datapath_working_multiplicand_reg[0] (.CK
       (u_datapath_rc_gclk_184), .D (multiplicand_in[0]), .Q
       (u_datapath_working_multiplicand[0]));
  AND2XL g667__4319(.A (u_controller_current_state[1]), .B
       (u_controller_current_state[0]), .Y (mult_complete));
  NAND2BX1 g668__8428(.AN (u_controller_current_state[0]), .B
       (u_controller_current_state[1]), .Y (n_39));
  OR2X1 g669__5526(.A (u_datapath_loop_counter[0]), .B
       (u_datapath_loop_counter[1]), .Y (n_38));
  NAND2BX1 g670__6783(.AN (u_controller_current_state[1]), .B
       (u_controller_current_state[0]), .Y (u_controller_n_13));
  DFFHQX1 \u_datapath_accumulated_prod_reg[7] (.CK (rc_gclk), .D
       (n_32), .Q (accumulated_prod[7]));
  AND2XL g1031__3680(.A (u_controller_n_13), .B (n_31), .Y (n_32));
  DFFHQX1 \u_datapath_accumulated_prod_reg[6] (.CK (rc_gclk), .D
       (n_30), .Q (accumulated_prod[6]));
  XNOR2X1 g1033__1617(.A (accumulated_prod[7]), .B (n_28), .Y (n_31));
  INVX1 g1034(.A (n_29), .Y (n_30));
  OAI211X1 g1035__2802(.A0 (accumulated_prod[6]), .A1 (n_26), .B0
       (u_controller_n_13), .C0 (n_28), .Y (n_29));
  DFFHQX1 \u_datapath_accumulated_prod_reg[5] (.CK (rc_gclk), .D
       (n_27), .Q (accumulated_prod[5]));
  NAND2X1 g1037__1705(.A (accumulated_prod[6]), .B (n_26), .Y (n_28));
  AOI211XL g1038__5122(.A0 (n_1), .A1 (n_22), .B0 (n_0), .C0 (n_26), .Y
       (n_27));
  DFFHQX1 \u_datapath_accumulated_prod_reg[4] (.CK (rc_gclk), .D
       (n_25), .Q (accumulated_prod[4]));
  NOR2X1 g1040__8246(.A (n_1), .B (n_22), .Y (n_26));
  NOR2X1 g1041__7098(.A (n_0), .B (n_24), .Y (n_25));
  DFFHQX1 \u_datapath_accumulated_prod_reg[3] (.CK (rc_gclk), .D
       (n_23), .Q (accumulated_prod[3]));
  OAI21X1 g1043__6131(.A0 (accumulated_prod[4]), .A1 (n_21), .B0
       (n_22), .Y (n_24));
  NOR2BX1 g1044__1881(.AN (n_20), .B (n_0), .Y (n_23));
  NAND2X1 g1045__5115(.A (accumulated_prod[4]), .B (n_21), .Y (n_22));
  ADDFX1 g1046__7482(.A (u_datapath_working_multiplicand[3]), .B
       (accumulated_prod[3]), .CI (n_17), .CO (n_21), .S (n_20));
  DFFHQX1 \u_datapath_accumulated_prod_reg[2] (.CK (rc_gclk), .D
       (n_19), .Q (accumulated_prod[2]));
  NOR2BX1 g1048__4733(.AN (n_18), .B (n_0), .Y (n_19));
  ADDFX1 g1049__6161(.A (u_datapath_working_multiplicand[2]), .B
       (accumulated_prod[2]), .CI (n_14), .CO (n_17), .S (n_18));
  DFFHQX1 \u_datapath_accumulated_prod_reg[1] (.CK (rc_gclk), .D
       (n_16), .Q (accumulated_prod[1]));
  NOR2BX1 g1051__9315(.AN (n_15), .B (n_0), .Y (n_16));
  ADDFX1 g1052__9945(.A (u_datapath_working_multiplicand[1]), .B
       (accumulated_prod[1]), .CI (n_6), .CO (n_14), .S (n_15));
  DFFHQX1 \u_controller_current_state_reg[1] (.CK (clk), .D (n_12), .Q
       (u_controller_current_state[1]));
  DFFHQX1 \u_controller_current_state_reg[0] (.CK (clk), .D (n_13), .Q
       (u_controller_current_state[0]));
  DFFHQX1 \u_datapath_accumulated_prod_reg[0] (.CK (rc_gclk), .D
       (n_11), .Q (accumulated_prod[0]));
  SDFFQX1 \u_datapath_loop_counter_reg[1] (.CK (rc_gclk), .D (n_9), .SI
       (multiplier_in[1]), .SE (n_0), .Q (u_datapath_loop_counter[1]));
  SDFFQX1 \u_datapath_loop_counter_reg[2] (.CK (rc_gclk), .D (n_7), .SI
       (multiplier_in[2]), .SE (n_0), .Q (u_datapath_loop_counter[2]));
  SDFFQX1 \u_datapath_loop_counter_reg[3] (.CK (rc_gclk), .D (n_8), .SI
       (multiplier_in[3]), .SE (n_0), .Q (u_datapath_loop_counter[3]));
  NOR2X1 g1059__2883(.A (reset), .B (n_10), .Y (n_13));
  AOI31X1 g1060__2346(.A0 (n_3), .A1 (n_39), .A2 (u_controller_n_13),
       .B0 (reset), .Y (n_12));
  NOR3X1 g1061__1666(.A (n_4), .B (n_6), .C (n_0), .Y (n_11));
  SDFFQX1 \u_datapath_loop_counter_reg[0] (.CK (rc_gclk), .D
       (multiplier_in[0]), .SI (n_2), .SE (u_controller_n_13), .Q
       (u_datapath_loop_counter[0]));
  AOI31X1 g1063__7410(.A0 (start), .A1 (n_39), .A2 (u_controller_n_13),
       .B0 (n_5), .Y (n_10));
  OAI2BB1X1 g1064__6417(.A0N (u_datapath_loop_counter[1]), .A1N
       (u_datapath_loop_counter[0]), .B0 (n_38), .Y (n_9));
  OAI2BB1X1 g1065__5477(.A0N (u_datapath_loop_counter[3]), .A1N (n_37),
       .B0 (n_36), .Y (n_8));
  OAI2BB1X1 g1066__2398(.A0N (u_datapath_loop_counter[2]), .A1N (n_38),
       .B0 (n_37), .Y (n_7));
  NOR2X1 g1067__5107(.A (n_39), .B (n_36), .Y (n_5));
  AND2XL g1068__6260(.A (u_datapath_working_multiplicand[0]), .B
       (accumulated_prod[0]), .Y (n_6));
  NOR2X1 g1069__4319(.A (u_datapath_working_multiplicand[0]), .B
       (accumulated_prod[0]), .Y (n_4));
  NAND2X1 g1070__8428(.A (start), .B (u_controller_current_state[0]),
       .Y (n_3));
  INVXL g1071(.A (u_datapath_loop_counter[0]), .Y (n_2));
  INVX1 g1072(.A (accumulated_prod[5]), .Y (n_1)); 
  INVX1 g1073(.A (u_controller_n_13), .Y (n_0));
endmodule
