// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Sep  6 2026 13:59:00 IST (Sep  6 2026 08:29:00 UTC)

// Verification Directory fv/top 

module top(clk, reset, start, multiplicand_in, multiplier_in,
     mult_complete, accumulated_prod);
  input clk, reset, start;
  input [3:0] multiplicand_in, multiplier_in;
  output mult_complete;
  output [7:0] accumulated_prod;
  wire clk, reset, start;
  wire [3:0] multiplicand_in, multiplier_in;
  wire mult_complete;
  wire [7:0] accumulated_prod;
  wire [3:0] u_datapath_loop_counter;
  wire [1:0] u_controller_current_state;
  wire [3:0] u_datapath_working_multiplicand;
  wire n_0, n_2, n_3, n_4, n_5, n_7, n_8, n_9;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_28, n_29, n_30, n_31, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_64, n_65, n_66, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_109, n_110, n_111, n_112;
  DFFQXL \u_datapath_accumulated_prod_reg[6] (.CK (clk), .D (n_97), .Q
       (accumulated_prod[6]));
  DFFQXL \u_datapath_accumulated_prod_reg[7] (.CK (clk), .D (n_94), .Q
       (accumulated_prod[7]));
  DFFHQX1 \u_datapath_loop_counter_reg[3] (.CK (clk), .D (n_96), .Q
       (u_datapath_loop_counter[3]));
  DFFHQX1 \u_datapath_accumulated_prod_reg[5] (.CK (clk), .D (n_95), .Q
       (accumulated_prod[5]));
  OAI211X1 g24136__2398(.A0 (n_50), .A1 (n_87), .B0 (n_90), .C0 (n_65),
       .Y (n_97));
  DFFHQX1 \u_datapath_accumulated_prod_reg[3] (.CK (clk), .D (n_93), .Q
       (accumulated_prod[3]));
  DFFQXL \u_datapath_accumulated_prod_reg[4] (.CK (clk), .D (n_92), .Q
       (accumulated_prod[4]));
  OAI2BB1X1 g24138__5107(.A0N (multiplier_in[3]), .A1N (n_71), .B0
       (n_91), .Y (n_96));
  NAND3XL g24135__6260(.A (n_76), .B (n_68), .C (n_80), .Y (n_95));
  NAND2X1 g24131__4319(.A (n_82), .B (n_88), .Y (n_94));
  DFFHQX1 \u_datapath_loop_counter_reg[2] (.CK (clk), .D (n_83), .Q
       (u_datapath_loop_counter[2]));
  DFFHQX1 \u_datapath_loop_counter_reg[1] (.CK (clk), .D (n_86), .Q
       (u_datapath_loop_counter[1]));
  DFFHQX1 \u_datapath_loop_counter_reg[0] (.CK (clk), .D (n_84), .Q
       (u_datapath_loop_counter[0]));
  OAI31X1 g24134__8428(.A0 (n_48), .A1 (n_85), .A2 (n_77), .B0 (n_78),
       .Y (n_93));
  OAI22X1 g24137__5526(.A0 (n_41), .A1 (n_69), .B0 (n_53), .B1 (n_81),
       .Y (n_92));
  OAI2BB1X1 g24144__6783(.A0N (n_89), .A1N (n_57), .B0
       (u_datapath_loop_counter[3]), .Y (n_91));
  OAI2BB1X1 g24167__3680(.A0N (n_89), .A1N (n_60), .B0
       (accumulated_prod[6]), .Y (n_90));
  OAI211X1 g24142__1617(.A0 (n_87), .A1 (n_64), .B0
       (accumulated_prod[7]), .C0 (n_39), .Y (n_88));
  DFFHQX1 \u_controller_current_state_reg[0] (.CK (clk), .D (n_70), .Q
       (u_controller_current_state[0]));
  OAI211X1 g24170__2802(.A0 (n_12), .A1 (n_85), .B0 (n_24), .C0 (n_55),
       .Y (n_86));
  OAI211X1 g24169__1705(.A0 (u_datapath_loop_counter[0]), .A1 (n_85),
       .B0 (n_26), .C0 (n_58), .Y (n_84));
  OAI2BB1X1 g24149__5122(.A0N (u_datapath_loop_counter[2]), .A1N
       (n_79), .B0 (n_72), .Y (n_83));
  DFFHQX1 \u_datapath_accumulated_prod_reg[1] (.CK (clk), .D (n_74), .Q
       (accumulated_prod[1]));
  DFFHQX1 \u_datapath_accumulated_prod_reg[2] (.CK (clk), .D (n_75), .Q
       (accumulated_prod[2]));
  OR4X1 g24150__8246(.A (accumulated_prod[7]), .B (n_62), .C (n_85), .D
       (n_81), .Y (n_82));
  AOI21X1 g24151__7098(.A0 (accumulated_prod[5]), .A1 (n_79), .B0
       (n_61), .Y (n_80));
  AOI22X1 g24143__6131(.A0 (n_49), .A1 (n_77), .B0
       (accumulated_prod[3]), .B1 (n_79), .Y (n_78));
  AOI22X1 g24171__1881(.A0 (n_73), .A1 (n_43), .B0
       (accumulated_prod[5]), .B1 (n_54), .Y (n_76));
  DFFHQX1 \u_datapath_accumulated_prod_reg[0] (.CK (clk), .D (n_56), .Q
       (accumulated_prod[0]));
  OAI22X1 g24141__5115(.A0 (n_85), .A1 (n_38), .B0 (n_0), .B1 (n_89),
       .Y (n_75));
  AO22XL g24157__7482(.A0 (n_73), .A1 (n_109), .B0
       (accumulated_prod[1]), .B1 (n_79), .Y (n_74));
  AOI22X1 g24158__4733(.A0 (n_112), .A1 (n_73), .B0 (multiplier_in[2]),
       .B1 (n_71), .Y (n_72));
  NOR2X1 g24145__6161(.A (reset), .B (n_47), .Y (n_70));
  AOI31X1 g24146__9315(.A0 (n_40), .A1 (n_110), .A2 (n_66), .B0 (n_79),
       .Y (n_69));
  NAND4X1 g24148__9945(.A (accumulated_prod[5]), .B (n_110), .C (n_73),
       .D (n_66), .Y (n_68));
  OR4X1 g24156__2883(.A (n_13), .B (n_52), .C (n_85), .D (n_51), .Y
       (n_65));
  OR4X1 g24187__2346(.A (mult_complete), .B (n_59), .C (n_62), .D
       (n_35), .Y (n_64));
  NOR3X1 g24152__1666(.A (n_111), .B (n_85), .C (n_66), .Y (n_61));
  OAI21XL g24191__7410(.A0 (n_36), .A1 (n_59), .B0 (n_73), .Y (n_60));
  NAND2X1 g24172__6417(.A (u_datapath_loop_counter[0]), .B (n_79), .Y
       (n_58));
  NAND2BXL g24164__5477(.AN (n_46), .B (n_73), .Y (n_57));
  OAI22X1 g24168__2398(.A0 (n_18), .A1 (n_85), .B0 (n_17), .B1 (n_89),
       .Y (n_56));
  NAND2X1 g24173__5107(.A (u_datapath_loop_counter[1]), .B (n_79), .Y
       (n_55));
  DFFHQX1 \u_controller_current_state_reg[1] (.CK (clk), .D (n_45), .Q
       (u_controller_current_state[1]));
  INVX1 g24178(.A (n_53), .Y (n_54));
  NOR2X1 g24154__6260(.A (n_52), .B (n_51), .Y (n_87));
  NOR2X1 g24153__4319(.A (n_21), .B (n_51), .Y (n_77));
  NAND2X1 g24190__8428(.A (n_34), .B (n_37), .Y (n_50));
  NOR2BX1 g24189__5526(.AN (n_48), .B (n_85), .Y (n_49));
  AOI22X1 g24160__6783(.A0 (n_46), .A1 (n_30), .B0 (start), .B1 (n_44),
       .Y (n_47));
  AND2X1 g24155__3680(.A (n_66), .B (n_110), .Y (n_81));
  AOI21X1 g24179__1617(.A0 (n_3), .A1 (n_44), .B0 (reset), .Y (n_45));
  NOR2X1 g24188__2802(.A (n_111), .B (n_110), .Y (n_43));
  NAND2X1 g24180__1705(.A (n_41), .B (n_40), .Y (n_53));
  SDFFQX1 \u_datapath_working_multiplicand_reg[2] (.CK (clk), .D
       (multiplicand_in[2]), .SI (u_datapath_working_multiplicand[2]),
       .SE (n_39), .Q (u_datapath_working_multiplicand[2]));
  INVX1 g24186(.A (n_89), .Y (n_79));
  XNOR2X1 g24159__5122(.A (n_23), .B (n_31), .Y (n_38));
  SDFFQX1 \u_datapath_working_multiplicand_reg[3] (.CK (clk), .D
       (multiplicand_in[3]), .SI (u_datapath_working_multiplicand[3]),
       .SE (n_39), .Q (u_datapath_working_multiplicand[3]));
  SDFFQX1 \u_datapath_working_multiplicand_reg[1] (.CK (clk), .D
       (multiplicand_in[1]), .SI (u_datapath_working_multiplicand[1]),
       .SE (n_39), .Q (u_datapath_working_multiplicand[1]));
  SDFFQX1 \u_datapath_working_multiplicand_reg[0] (.CK (clk), .D
       (multiplicand_in[0]), .SI (u_datapath_working_multiplicand[0]),
       .SE (n_39), .Q (u_datapath_working_multiplicand[0]));
  INVX2 g24197(.A (n_85), .Y (n_73));
  NOR4X1 g24198__8246(.A (accumulated_prod[6]), .B (n_36), .C (n_59),
       .D (n_29), .Y (n_37));
  NAND2XL g24195__7098(.A (u_controller_current_state[1]), .B (n_34),
       .Y (n_35));
  AOI21X1 g24193__6131(.A0 (n_5), .A1 (n_28), .B0 (n_44), .Y (n_89));
  NAND2X4 g24200__1881(.A (n_20), .B (n_34), .Y (n_85));
  NOR2BX1 g24165__4733(.AN (n_31), .B (n_22), .Y (n_51));
  NAND2X2 g24166__6161(.A (n_19), .B (n_31), .Y (n_66));
  NOR2X1 g24210__9945(.A (u_datapath_loop_counter[3]), .B (n_29), .Y
       (n_30));
  NOR2X1 g24199__2883(.A (n_29), .B (n_28), .Y (n_40));
  NAND2X1 g24201__1666(.A (multiplier_in[0]), .B (n_71), .Y (n_26));
  OAI21X1 g24177__7410(.A0 (n_9), .A1 (n_15), .B0 (n_14), .Y (n_31));
  NOR2X1 g24182__6417(.A (u_datapath_loop_counter[2]), .B (n_25), .Y
       (n_46));
  NAND2X1 g24209__5477(.A (multiplier_in[1]), .B (n_71), .Y (n_24));
  NOR2XL g24203__2398(.A (n_22), .B (n_21), .Y (n_23));
  NOR2X1 g24213__5107(.A (n_71), .B (n_20), .Y (n_44));
  INVX2 g24207(.A (n_28), .Y (n_34));
  NOR2X1 g24202__6260(.A (n_22), .B (n_59), .Y (n_19));
  MX2XL g24208__4319(.A (n_17), .B (accumulated_prod[0]), .S0
       (u_datapath_working_multiplicand[0]), .Y (n_18));
  NAND2BX1 g24212__8428(.AN (n_15), .B (n_14), .Y (n_16));
  OR2XL g24205__5526(.A (n_13), .B (n_36), .Y (n_62));
  NOR2BX1 g24204__6783(.AN (n_11), .B (n_59), .Y (n_48));
  AOI21X1 g24211__3680(.A0 (u_datapath_loop_counter[1]), .A1
       (u_datapath_loop_counter[0]), .B0 (n_7), .Y (n_12));
  NAND2X1 g24206__1617(.A (n_11), .B (n_8), .Y (n_52));
  CLKAND2X2 g24214__2802(.A (n_4), .B (n_2), .Y (n_28));
  INVX1 g24227(.A (n_20), .Y (n_29));
  INVX1 g24218(.A (n_71), .Y (n_39));
  INVX1 g24216(.A (n_8), .Y (n_21));
  INVX1 g24215(.A (n_7), .Y (n_25));
  CLKAND2X2 g24235__5122(.A (u_controller_current_state[1]), .B (n_5),
       .Y (n_20));
  NOR2X1 g24226__8246(.A (u_controller_current_state[1]), .B (n_5), .Y
       (n_71));
  NOR2X1 g24219__7098(.A (u_datapath_loop_counter[3]), .B
       (u_datapath_loop_counter[1]), .Y (n_4));
  NAND2X1 g24228__6131(.A (start), .B (u_controller_current_state[0]),
       .Y (n_3));
  NOR2XL g24229__1881(.A (u_datapath_loop_counter[0]), .B
       (u_datapath_loop_counter[2]), .Y (n_2));
  NOR2X1 g24223__5115(.A (u_datapath_loop_counter[1]), .B
       (u_datapath_loop_counter[0]), .Y (n_7));
  NOR2X1 g24220__7482(.A (u_datapath_working_multiplicand[1]), .B
       (accumulated_prod[1]), .Y (n_15));
  NAND2X1 g24224__4733(.A (u_datapath_working_multiplicand[2]), .B
       (accumulated_prod[2]), .Y (n_8));
  NAND2X1 g24230__6161(.A (u_datapath_working_multiplicand[3]), .B
       (accumulated_prod[3]), .Y (n_11));
  AND2X1 g24231__9315(.A (u_controller_current_state[1]), .B
       (u_controller_current_state[0]), .Y (mult_complete));
  NAND2X1 g24221__9945(.A (u_datapath_working_multiplicand[1]), .B
       (accumulated_prod[1]), .Y (n_14));
  NAND2X1 g24232__2883(.A (u_datapath_working_multiplicand[0]), .B
       (accumulated_prod[0]), .Y (n_9));
  NOR2X1 g24233__2346(.A (u_datapath_working_multiplicand[2]), .B
       (accumulated_prod[2]), .Y (n_22));
  NAND2X1 g24234__1666(.A (accumulated_prod[5]), .B
       (accumulated_prod[4]), .Y (n_36));
  NOR2X1 g24225__7410(.A (u_datapath_working_multiplicand[3]), .B
       (accumulated_prod[3]), .Y (n_59));
  INVX1 g24239(.A (accumulated_prod[0]), .Y (n_17));
  INVX1 g24238(.A (accumulated_prod[6]), .Y (n_13));
  INVX1 g24240(.A (u_controller_current_state[0]), .Y (n_5));
  INVX1 g24236(.A (accumulated_prod[2]), .Y (n_0));
  INVX1 g24237(.A (accumulated_prod[4]), .Y (n_41));
  XOR2XL g2(.A (n_9), .B (n_16), .Y (n_109));
  NAND2BX1 g24260(.AN (n_59), .B (n_52), .Y (n_110));
  NAND2BX1 g24261(.AN (accumulated_prod[5]), .B (accumulated_prod[4]),
       .Y (n_111));
  AO21XL g24262(.A0 (u_datapath_loop_counter[2]), .A1 (n_25), .B0
       (n_46), .Y (n_112));
endmodule
